sonar.projectKey=NafNawal04_RainQuote
sonar.organization=nafnawal04
sonar.sources=Frontend/src,Backend
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,**/public/**
sonar.javascript.lcov.reportPaths=Frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8